### ISSUE TITLE
Copying incomplete passwords

### ISSUE THREAD

**Issue by Inesgor** [salman-abedin/unipass#1]
Assalaamu Alaikum. 
I was trying unipass and I really liked it. I use very long passwords and i use [mutt-wizard](https://github.com/LukeSmithxyz/mutt-wizard), so I tried decrypting the passwords mutt-wizard stored (it also uses pass). However, `unipass fetch` only copied the last few characters of my password and not all of it, and this happens for every such password in mutt-wizard folder. I then tried adding (`unipass add`) long password manually, and it worked. So I guess the problem only exists when passwords created by mutt-wizard are decrypted.
Is there anything wrong I am doing?
Thanks.

**Comment by Inesgor** [comment]
Update: I tried again. This time i cloned the updated repo (I was using an old clone earlier) & I made a new password, independent of mutt-wizard. `cccccc,444444.,{|l0/` was the testing password and it copied only `444444.,{|l0/` part of it. So the problem isn't limited to mutt-wizard.

**Comment by salman-abedin** [comment]
Walaikum Assalam brother.  
You are facing the issue due to the script parsing the account names, usernames & passwords as comma separated lines.

P.S.: If you leave the password while adding, it will generate a random password for you.
